import { z } from "zod";
import { Id, ItemBag, JsonObject, LocKey, SchemaVersion, Tier } from "./common";

export const TutorialStep = z.strictObject({
  trigger: z.enum(["start", "first_move", "first_category", "first_mismatch"]),
  textKey: LocKey,
});

export const LevelAnalysis = z.strictObject({
  solutionLength: z.int().nonnegative().describe("Moves in the solver's solution (perfect information)"),
  solverNodes: z.int().nonnegative(),
  botWinRate: z.partialRecord(z.enum(["casual", "average", "expert"]), z.number().min(0).max(1)).optional(),
  generator: z.strictObject({ id: z.string(), seed: z.string() }),
});

export const LevelDefinition = z
  .strictObject({
    levelId: Id,
    number: z.int().positive(),
    mechanic: Id,
    difficulty: z.strictObject({ tier: Tier, score: z.number().min(0).max(1) }),
    objectives: z.array(z.strictObject({ type: z.literal("clear_board") })).min(1),
    lose: z.strictObject({ outOfMoves: z.boolean(), stuck: z.boolean() }),
    boosters: z.strictObject({ allowed: z.array(Id) }),
    reward: ItemBag.optional().describe("Overrides the economy's star-based level reward"),
    tags: z.array(z.string()).default([]),
    tutorial: z.strictObject({ steps: z.array(TutorialStep).min(1) }).optional(),
    data: JsonObject.describe("Mechanic-specific payload, validated by the mechanic's own schema"),
    analysis: LevelAnalysis.optional(),
  })
  .meta({ title: "LevelDefinition", description: "One level: generic envelope plus mechanic payload" });
export type LevelDefinition = z.infer<typeof LevelDefinition>;

export const LevelsFile = z
  .strictObject({
    $schema: z.string().optional(),
    schemaVersion: SchemaVersion,
    levels: z.array(LevelDefinition),
  })
  .meta({ title: "LevelsFile", description: "games/ID/levels.json (generated by gf levels generate)" });
export type LevelsFile = z.infer<typeof LevelsFile>;

export const DifficultyTarget = z.strictObject({
  profile: z.enum(["casual", "average", "expert"]),
  winRate: z.number().min(0).max(1).describe("Win rate the move budget is tuned to, measured with bot players"),
});
export type DifficultyTarget = z.infer<typeof DifficultyTarget>;

export const CurveSegment = z.strictObject({
  from: z.int().positive(),
  to: z.int().positive(),
  tier: Tier,
  params: JsonObject.describe("Generator parameters for this range; merged over defaults"),
  target: DifficultyTarget.optional().describe("Rebalance the budget so this bot profile wins at this rate"),
});

export const LevelGenConfig = z
  .strictObject({
    $schema: z.string().optional(),
    schemaVersion: SchemaVersion,
    mechanic: Id,
    seed: z.string().min(1),
    count: z.int().positive(),
    defaults: JsonObject.describe("Generator parameters shared by every level"),
    curve: z.array(CurveSegment).min(1),
    keystones: z.array(z.int().positive()).default([]).describe("Level numbers that get the keystone tag"),
    boosters: z.strictObject({ allowed: z.array(Id) }),
    tutorials: z.record(z.string().regex(/^\d+$/), z.array(TutorialStep)).default({}),
  })
  .meta({ title: "LevelGenConfig", description: "games/ID/levelgen.json: difficulty curve for the generator" });
export type LevelGenConfig = z.infer<typeof LevelGenConfig>;
